import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

public class FindDigits {

	public static void main(String[] args) {
		// TODO Autogenerated method stub
		System.out.println(findDigits(1012));
	}

	public static int findDigits(int d) {
		List<Integer> arrNums = new ArrayList<>();
		int dCopy = d;
		while (dCopy > 0) {
			int num = dCopy % 10;
			dCopy = dCopy / 10;
			arrNums.add(num);
		}
		int count = 0;
		for (int i : arrNums) {
			if (i != 0) {
				if (d % i == 0)
					count++;
			}
		}
		return count;
	}
	
	public static void extraLongFactorials(int n) {
		// Write your code here
		BigInteger factValue = BigInteger.valueOf(1);
		for (int i = 1; i <= n; i++) {
			factValue = factValue.multiply(BigInteger.valueOf(i));
		}
		System.out.println(factValue);
	}
}
